In [ ]:
#import all libraries which is required
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#import dataset
df = pd.read_csv("/content/House price prediction(unstable data) - Sheet1 (1).csv")

In [ ]:
#show data
df

Area    price
0    500  2000000
1    550  2500000
2    600  3000000
3    650  3500000
4    700  4000000
5    750  4500000
6    800  5000000
7    850  5500000
8    900  6000000
9    950  6500000
10  1000  7000000
11   250   800000
12   722  4200000
13   333   900000
14   820  8200000
15   454  2300000
16   590  6600000
17   120   500000
18   636  5400000
19   990  8800000
20   364  6600000
21   478  3200000
22   570  7700000
23   789  7800000
24   888  4300000
25   342  5400000
26   444  6500000
27   765  9000000
28   908  9900000

In [ ]:
# show first 5 rows of data
df.head()

Area    price
0   500  2000000
1   550  2500000
2   600  3000000
3   650  3500000
4   700  4000000

In [ ]:
#gives matrix of data
df.shape

(29, 2)

In [ ]:
#gives statistical summary
df.describe()

Area         price
count    29.000000  2.900000e+01
mean    645.275862  5.089655e+06
std     233.641345  2.562692e+06
min     120.000000  5.000000e+05
25%     478.000000  3.200000e+06
50%     650.000000  5.400000e+06
75%     820.000000  6.600000e+06
max    1000.000000  9.900000e+06

In [ ]:
#check for the null values
df.isnull().sum()

Area     0
price    0
dtype: int64

In [ ]:
X = df[["Area"]]  # Input features (2D) - Area column as DataFrame
y = df['price']    # Target variable (1D) - price column as Series

In [ ]:
X = df.iloc[:,0:1].values # Select first column as 2D NumPy array (features)

In [ ]:
X

array([[ 500],
       [ 550],
       [ 600],
       [ 650],
       [ 700],
       [ 750],
       [ 800],
       [ 850],
       [ 900],
       [ 950],
       [1000],
       [ 250],
       [ 722],
       [ 333],
       [ 820],
       [ 454],
       [ 590],
       [ 120],
       [ 636],
       [ 990],
       [ 364],
       [ 478],
       [ 570],
       [ 789],
       [ 888],
       [ 342],
       [ 444],
       [ 765],
       [ 908]])

In [ ]:
y = df.iloc[:,-1].values # Select last column as 1D NumPy array (target)

In [ ]:
y

array([2000000, 2500000, 3000000, 3500000, 4000000, 4500000, 5000000,
       5500000, 6000000, 6500000, 7000000,  800000, 4200000,  900000,
       8200000, 2300000, 6600000,  500000, 5400000, 8800000, 6600000,
       3200000, 7700000, 7800000, 4300000, 5400000, 6500000, 9000000,
       9900000])

In [ ]:
# Split data into training and testing sets (80% train, 20% test)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=42)

In [ ]:
# train the model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
# Predict target values for test data
y_pred = regressor.predict(X_test)

In [ ]:
y_pred

array([5775545.31373964, 4468481.12676064, 5454380.97065337,
       4319102.36253447, 6783851.9722663 , 7157298.88283173])

In [ ]:
#Evaluate Model
from sklearn.metrics import mean_squared_error, r2_score # tells error
mse = mean_squared_error(y_test, y_pred) #gives accuracy
r2_score(y_test, y_pred)


-1.2175589179814064

In [ ]:
mse

4831814486846.153